-- Drop tables if they exist
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS adClicks;
DROP TABLE IF EXISTS ads;
DROP TABLE IF EXISTS adCategories;
DROP TABLE IF EXISTS advertisers;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS locations;

-- Create tables
CREATE TABLE advertisers (
    id INT AUTO_INCREMENT PRIMARY KEY,
    advertiserName VARCHAR(255) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE adCategories (
    id INT AUTO_INCREMENT PRIMARY KEY,
    category VARCHAR(255) NOT NULL UNIQUE,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    contact VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    vehicles JSON NOT NULL,
    cardDetails JSON,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE locations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    lat FLOAT,
    lng FLOAT,
    address VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE ads (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    advertiserId INT NOT NULL,
    adUrl VARCHAR(255) NOT NULL,
    imageUrl VARCHAR(255),
    locationIds JSON NOT NULL,
    costToClick FLOAT NOT NULL CHECK (costToClick >= 0),
    categoryId INT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (advertiserId) REFERENCES advertisers(id) ON DELETE CASCADE,
    FOREIGN KEY (categoryId) REFERENCES adCategories(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE adClicks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    adId BIGINT NOT NULL,
    memberId INT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    isClicked BOOLEAN DEFAULT false,
    transactionId BIGINT NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (adId) REFERENCES ads(id) ON DELETE CASCADE,
    FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    locationId BIGINT NOT NULL,
    memberId INT NOT NULL,
    vehicleNumber VARCHAR(255) NOT NULL,
    entryTime TIMESTAMP NOT NULL,
    exitTime TIMESTAMP NULL,
    vehicleDetails JSON,
    total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    discount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    serviceFee DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    paid DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (locationId) REFERENCES locations(id) ON DELETE RESTRICT,
    FOREIGN KEY (memberId) REFERENCES members(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Create indexes
CREATE INDEX idx_ads_advertiserId ON ads(advertiserId);
CREATE INDEX idx_ads_categoryId ON ads(categoryId);
CREATE INDEX idx_adClicks_adId ON adClicks(adId);
CREATE INDEX idx_adClicks_memberId ON adClicks(memberId);
CREATE INDEX idx_transactions_locationId ON transactions(locationId);
CREATE INDEX idx_transactions_memberId ON transactions(memberId);
CREATE INDEX idx_transactions_vehicleNumber ON transactions(vehicleNumber);
CREATE INDEX idx_members_contact ON members(contact); 